### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by acarlton5** [stephenmcd/gnotty#25]
When using Pip it says

Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-4mSy0H/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-tPovNw-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-4mSy0H/gevent
Storing debug log for failure in /root/.pip/pip.log

**Comment by stephenmcd** [comment]
Can't reproduce, likely an issue with your environment, not the software.

**Comment by acarlton5** [comment]
Thank you for the quick reply :+1: May i ask what environment you are using
